---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nexus-exporter
  name: nexus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-exporter
  template:
    metadata:
      labels:
        app: nexus-exporter
    spec:
      containers:
        - name: nexus-exporter
          image: nexus.ap-team.ru/ocadotechnology/nexus-exporter:0.2.2
          imagePullPolicy: Always
          ports:
          - containerPort: 9184
            protocol: TCP
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 100Mi
          env: 
            - name: NEXUS_HOST
              value: nexus-nexus-repository-manager.nexus:8081
            - name: NEXUS_USERNAME
              value: admin
            - name: NEXUS_ADMIN_PASSWORD
              value: admin
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nexus-exporter
  name: nexus-exporter
spec:
  ports:
  - name: http
    port: 9184
    protocol: TCP
  selector:
    app: nexus-exporter